CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE roles (
    role_id integer GENERATED BY DEFAULT AS IDENTITY,
    role_name text NOT NULL,
    CONSTRAINT "PK_roles" PRIMARY KEY (role_id)
);

CREATE TABLE users (
    user_id uuid NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    role_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_users" PRIMARY KEY (user_id),
    CONSTRAINT "FK_users_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE RESTRICT
);

CREATE TABLE refresh_tokens (
    refresh_token_id uuid NOT NULL,
    user_id uuid NOT NULL,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_refresh_tokens" PRIMARY KEY (refresh_token_id),
    CONSTRAINT "FK_refresh_tokens_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE RESTRICT
);

CREATE TABLE task_items (
    task_item_id uuid NOT NULL,
    title text NOT NULL,
    description text,
    assignee_id uuid NOT NULL,
    deadline date NOT NULL,
    priority integer NOT NULL,
    status integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_task_items" PRIMARY KEY (task_item_id),
    CONSTRAINT "FK_task_items_users_assignee_id" FOREIGN KEY (assignee_id) REFERENCES users (user_id) ON DELETE RESTRICT
);

CREATE TABLE worklos (
    worklog_id uuid NOT NULL,
    task_item_id uuid NOT NULL,
    user_id uuid NOT NULL,
    work_date date NOT NULL,
    hours_spent numeric NOT NULL,
    note text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_worklos" PRIMARY KEY (worklog_id),
    CONSTRAINT ck_worklogs_hoursspent CHECK (hours_spent > 0 AND  hours_spent <= 8),
    CONSTRAINT "FK_worklos_task_items_task_item_id" FOREIGN KEY (task_item_id) REFERENCES task_items (task_item_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_worklos_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE RESTRICT
);

INSERT INTO roles (role_id, role_name)
VALUES (1, 'ADMIN');
INSERT INTO roles (role_id, role_name)
VALUES (2, 'LEADER');
INSERT INTO roles (role_id, role_name)
VALUES (3, 'MEMBER');

CREATE UNIQUE INDEX "IX_refresh_tokens_token" ON refresh_tokens (token);

CREATE INDEX "IX_refresh_tokens_user_id_expires_at" ON refresh_tokens (user_id, expires_at);

CREATE UNIQUE INDEX "IX_roles_role_name" ON roles (role_name);

CREATE INDEX "IX_task_items_assignee_id_deadline" ON task_items (assignee_id, deadline);

CREATE INDEX "IX_task_items_status" ON task_items (status);

CREATE UNIQUE INDEX "IX_users_email" ON users (email);

CREATE INDEX "IX_users_role_id" ON users (role_id);

CREATE UNIQUE INDEX "IX_worklos_task_item_id_user_id_work_date" ON worklos (task_item_id, user_id, work_date);

CREATE INDEX "IX_worklos_user_id" ON worklos (user_id);

SELECT setval(
    pg_get_serial_sequence('roles', 'role_id'),
    GREATEST(
        (SELECT MAX(role_id) FROM roles) + 1,
        nextval(pg_get_serial_sequence('roles', 'role_id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260205102238_InitialCreate', '9.0.12');

COMMIT;

